services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
